import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col justify-between w-full bg-blue-50`}
      >
        <header className="px-3 py-1.5 bg-secondary w-full">
          <nav className="mx-auto max-w-5xl flex justify-between items-center">
            <div>
              <Link href={"/"}>
                <Image
                  src={"https://www.elsolnec.org/wp-content/uploads/2020/08/cropped-el_sol_4color_wide_web.png"}
                  alt="elsolnec"
                  className="w-32 block md:w-48" width={200} height={100}
                />
              </Link>
            </div>
            <ul className="flex items-center justify-end gap-2">
              <li className="hover:underline hover:text-foreground">
                <Link
                  href={"/users"}
                >
                  Usuarios
                </Link>
              </li>
              <li className="hover:underline hover:text-foreground">
                <Link
                  href={"/posts"}
                >
                  Publicaciones
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="mx-auto max-w-5xl w-full py-10 flex-12/12 px-5 md:px-10 xl:px-0">
          <Providers>
            {children}
          </Providers>
        </main>
        <footer className="bg-secondary py-5 px-2">
          <h3 className="mx-auto max-w-5xl text-center">
            <span>
              Hecho por:
            </span>
            <Link 
              href={"https://christian-aguilar-portfolio.vercel.app/"} target="_blank"
              className="font-medium hover:text-primary hover:underline ml-1"
            >
              Christian Aguilar
            </Link>
          </h3>
        </footer>
      </body>
    </html>
  );
}
